import type { Metadata } from "next";
// import { Plus_Jakarta_Sans } from 'next/font/google';
import { Bricolage_Grotesque } from 'next/font/google';
import "./globals.css";
import Providers from "./provider";
import { ThemeProvider } from "@/context/ThemeContext";

export const metadata: Metadata = {
  title: "Final year Project",
  description: "Generated by create next app",
};

// const jakarta = Plus_Jakarta_Sans({
//   subsets: ['latin'],
//   weight: ['300', '400', '500', '600', '700', '800'],
//   variable: '--font-jakarta', // This creates a CSS variable
// });

const bricolage = Bricolage_Grotesque({
  subsets: ['latin'],
  display: 'swap',
  // Fancy weights for that high-contrast look
  weight: ['200', '400', '600', '800'], 
  variable: '--font-bricolage',
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {


  return (
    <html  lang="en"  className={bricolage.variable}>
      <body className={bricolage.className} suppressContentEditableWarning={true}>
       <ThemeProvider>
         <Providers>{children}</Providers>
       </ThemeProvider>
      </body>
    </html>
  );
}
